export const UPDATE_CART = 'UPDATE_CART';
export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';
export const ADD_SERVICE_REQUEST = 'ADD_SERVICE_REQUEST';
export const ADD_SERVICE_FAILURE = 'ADD_SERVICE_FAILURE';
export const ADD_SERVICE_SUCCESS = 'ADD_SERVICE_SUCCESS';
export const FETCH_SERVICES_REQUEST = 'FETCH_SERVICES_REQUEST';
export const FETCH_SERVICES_FAILURE = 'FETCH_SERVICES_FAILURE';
export const FETCH_SERVICES_SUCCESS = 'FETCH_SERVICES_SUCCESS';